# Generated by Django 3.2.25 on 2024-05-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
    ]
