# Generated by Django 3.2.25 on 2024-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantSystem', '0003_auto_20240512_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
