# Generated by Django 3.2.25 on 2024-05-12 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantSystem', '0004_order_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='restaurantSystem.reservation'),
        ),
    ]
